### ISSUE TITLE
Krav: Registrera ny kund

### ISSUE THREAD

**Issue by erikdsp** [erikdsp/boilerroom-alarmdatabase#1]

**Comment by NewNamesAreHard** [comment]
- **Primary**:
- [x] Input handling
- [x] Functionality to add a [struct]& customer
- [x] Ability to print [struct]& customer (has to exist before more advanced duplication checking logic exist)
- [x] Tests for basic functionality
- **Secondary**:
- [ ] Test ability to take input, write to (in main defined) struct
- [ ] Input error handling
